# Generated by Django 5.1.1 on 2024-10-22 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
